# Build settings
# plugins : https://pages.github.com/versions/
# gem 'github-pages', group: :jekyll_plugins

# Site settings
title: Carbon
email: animationfar@gmail.com
description: >-
  is a main project which handle and unite any project 
  in any form for any purpose. Such as carbon which stable, 
  flexible, and could form many other compounds, this main 
  project is expected to be able to make many other projects 
  such as applications, services, tools, or papers.
baseurl: "/blog.html"
url: "https://carbon4.github.io"

# defaults
defaults:
  -
    scope:
      path: "" 
      type: ""
    values:
      layout: "post"
